hotelmanager/urls.py
from django.conf.urls import patterns, include, url
from hotelmanager import views
from django.contrib.auth.decorators import login_required, permission_required
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'hotelmanager.views.home', name='home'),
    # url(r'^hotelmanager/', include('hotelmanager.foo.urls')),


    url(r'^admin/', include(admin.site.urls)),

    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^rooms/', include('rooms.urls', namespace='rooms')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^(?P<slug>.+)/$', views.HotelView.as_view(), name='detail'),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rooms/urls.py
from django.conf.urls import patterns, url
from django.conf import settings
from django.conf.urls.static import static
from rooms import views

from django.contrib.auth.decorators import login_required, permission_required


urlpatterns = patterns('',
        url(r'^$', login_required(views.IndexView.as_view()), name='index'),
        url(r'^add/$', login_required(views.add_room), name='add_room'),
        url(r'^(?P<slug>\w+)/$', login_required(views.DetailView.as_view()), name='detail'),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotelmanager/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User




class Hotel(models.Model):
    name = models.CharField(max_length=100)
    slugp = models.SlugField(max_length=255, unique=True, default=u"generic")

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slugp = slugify(self.name)
        super(Hotel, self).save(*args, **kwargs)


class UserProfile(models.Model):
    hotels = models.ManyToManyField(Hotel)

    user = models.OneToOneField(User)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='users_img', blank=True)

    def __unicode__(self):
        return self.user.username

hotelmanager/forms.py
#forms

from .models import UserProfile
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

hotelmanager/views.py
from django.views.generic import TemplateView, DetailView
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render
from hotelmanager.models import Hotel
from .forms import UserForm, UserProfileForm
from rooms.models import Room, RoomForm


class HomeView(TemplateView):
    template_name = "home.html"


class HotelView(DetailView):
    model = Hotel
    slug_field = "slugp"
    template_name = "detail.html"


    def get_context_data(self, **kwargs):
        context = super(HotelView, self).get_context_data(**kwargs)
        context['all_rooms_list'] = Room.objects.filter(hotel__slugp=self.kwargs['slug'])
        context['room_form'] = RoomForm
        return context

def login_view(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            login(request, user)
            return HttpResponseRedirect('/')
            # Redirect to success page
        else:
            return HttpResponse("Account disabled")
            # 'Disabled account' error message
    else:
        return HttpResponse("Invalid login")
        # 'Invalid login' error message

@login_required
def logout_view(request):
    logout(request)

    return HttpResponseRedirect('/')

def register_view(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            profile.save()
            registered = True
        else:
            print user_form.errors, profile_form.errors

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request, 'registration.html',
            {'user_form': user_form, 'profile_form': profile_form, 'registered': registered}
            )

hotelmanager/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Rooms</title>

	<!-- Bootstrap core CSS -->
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

	<!-- Custom styles for this template -->
	<link href="{% static 'css/starter-template.css' %}" rel="stylesheet">
	<link href="{% static 'css/signin.css' %}" rel="stylesheet">
    <link href="{% static 'css/jumbotron.css' %}" rel="stylesheet">




    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Hotel Manager</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
            {% if user.is_authenticated %}
              <li><a href="{% url 'rooms:index' %}">Rooms</a></li>
            {% endif %}
          </ul>
          {% if user.is_authenticated %}
              <a href="/logout/"><button type="button" class="btn btn-primary">logout {{ user.username }}</button></a>
          {% else %}

              <form id="login_form" method="post" action="/login/" class="navbar-form navbar-right" role="form">
                  {% csrf_token %}
                <div class="form-group">
                  <input type="text" name="username" class="form-control">
                </div>
                <div class="form-group">
                  <input type="password" name="password" placeholder="Password" class="form-control">
                </div>
                <button type="submit" class="btn btn-success">Sign in</button>
                <a href="{% url 'registration_register' %}"><button type="button" class="btn btn-primary">Register</button></a>
              </form>

            {% endif %}

        </div><!--/.nav-collapse -->
      </div>
    </div>


{% block content %}
{% endblock %}


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

hotelmanager/templates/detail.html
{% extends "base.html" %}

{% block content %}
{% load bootstrap_tags %}


<div class="container">

  <div class="starter-template">

    <div class="panel panel-default">
      <!-- Default panel contents -->
      <div class="panel-heading">{{ hotel.name }}</div>
      <div class="panel-body">
      </div>
      <!-- Table -->
      <table class="table table-bordered">
      {% if all_rooms_list %}
          <tr class="info">
              <td>Number</a></td>
              <td>Available</a></td>
              <td>Prepared</td>
              <td>Condignation</td>
              <td>Equipment</td>
          </tr>

          {% for room in all_rooms_list %}
          {% if room.available %}
              <tr class="success">
          {% else %}
              <tr>
          {% endif %}
              <td><a href="{% url 'rooms:detail' room.number %}">{{ room.number }}</a></td>
              <td>{{ room.available }}</a></td>
              <td>{{ room.prepared }}</td>
              <td>{{ room.condignation }}</td>
              <td>
              {% if room.equipments.all %}
                  {% for e in room.equipments.all %}
                      {{ e }},
                  {% endfor %}
              {% else %}
                  None
              {% endif %}
              </td>
          </tr>
          {% endfor %}
      {% else %}
          <tr><td>No rooms are available.</td></tr>
      {% endif %}
      </table>
    </div>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

  </div>
<form class="form-signin" role="form" action="/rooms/add/" method="post" enctype="multipart/form-data">
    <legend>My Form</legend>
    {% csrf_token %}
    {{ room_form|as_bootstrap }}
    <div class="form-actions">
      <a href="#back" class="btn">Go back</a>
      <button type="submit" class="btn btn-primary">Save changes</button>
    </div>
</form>




</div><!-- /.container -->


{% endblock %}

hotelmanager/templates/home.html
{% extends "base.html" %}
{% block content %}
    <div class="container">

      <div class="starter-template">
        <h1>Hotel Manager</h1>
        <p class="lead">This is a home page of Hotel Manager Project</p>
        {% if user.is_authenticated %}
            <p>Twoje hotele:</p>
            {% for h in user.userprofile.hotels.all %}
                <p><a href="{% url 'detail' h.name|slugify %}">{{ h.name }}</a></p>
            {% endfor %}
        {% else %}
        <p>Login as tadek (password=tadek) or register (fill in all the fields)</p>
        <p>Then you are welcome to taste the "rooms" functionality (link will appear on the top menu)</p>
        {% endif %}
      </div>

    </div><!-- /.container -->
{% endblock %}

hotelmanager/templates/registration.html
{% extends "base.html" %}
{% block content %}
{% load bootstrap_tags %}
<div class="container">

  <div class="starter-template">
    
    {% if registered %}
        <p>Thank you for registering.</p>
    {% else %}
        <form class="form-signin" role="form" action="/register/" method="post" enctype="multipart/form-data">
        <legend>Registration</legend>
        {% csrf_token %}
        {{ user_form|as_bootstrap }}
        {{ profile_form|as_bootstrap }}
        <div class="form-actions">
          <a href="#back" class="btn">Go back</a>
          <button type="submit" class="btn btn-primary">Save changes</button>
    {% endif %}
    </div>
</form>
    
  </div>

</div><!-- /.container -->

{% endblock %}