hotelmanager/urls.py
from django.conf.urls import patterns, include, url
from hotelmanager import views
from django.contrib.auth.decorators import login_required, permission_required
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'hotelmanager.views.home', name='home'),
    # url(r'^hotelmanager/', include('hotelmanager.foo.urls')),


    url(r'^admin/', include(admin.site.urls)),

    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^rooms/', include('rooms.urls', namespace='rooms')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^(?P<slug>.+)/$', views.HotelView.as_view(), name='detail'),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rooms/urls.py
from django.conf.urls import patterns, url
from django.conf import settings
from django.conf.urls.static import static
from rooms import views

from django.contrib.auth.decorators import login_required, permission_required


urlpatterns = patterns('',
        url(r'^$', login_required(views.IndexView.as_view()), name='index'),
        url(r'^add/$', login_required(views.add_room), name='add_room'),
        url(r'^(?P<slug>\w+)/$', login_required(views.DetailView.as_view()), name='detail'),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotelmanager/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User




class Hotel(models.Model):
    name = models.CharField(max_length=100)
    slugp = models.SlugField(max_length=255, unique=True, default=u"generic")

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slugp = slugify(self.name)
        super(Hotel, self).save(*args, **kwargs)


class UserProfile(models.Model):
    hotels = models.ManyToManyField(Hotel)

    user = models.OneToOneField(User)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='users_img', blank=True)

    def __unicode__(self):
        return self.user.username

rooms/models.py
from django.db import models
from django.forms import ModelForm

#from django.contrib.auth.models import User

from hotelmanager.models import Hotel


class RoomType(models.Model):
    name = models.CharField(max_length=100, unique=True)
    beds = models.IntegerField(null=True)


    def __unicode__(self):
        return u"%s with %s beds" % (self.name, self.beds)


class Equipment(models.Model):
    name = models.CharField(max_length=100)

    def __unicode__(self):
        return self.name



class Room(models.Model):
    hotel = models.ForeignKey(Hotel, default=1)
    roomtype = models.ForeignKey(RoomType, default=1)
    number = models.CharField(max_length=100, unique=True)
    available = models.BooleanField(default=True)
    prepared = models.BooleanField(default=True)
    windowview = models.CharField(max_length=100, null=True)
    condignation = models.IntegerField(null=True)
    cost = models.IntegerField(null=True)
    equipments = models.ManyToManyField(Equipment, null=True)
    img = models.ImageField(null=True, upload_to='room_type_img')

    def __unicode__(self):
        return self.number


class RoomForm(ModelForm):
    class Meta:
        model = Room


class RoomTypeForm(ModelForm):
    class Meta:
        model = RoomType

hotelmanager/forms.py
#forms

from .models import UserProfile
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

hotelmanager/views.py
from django.views.generic import TemplateView, DetailView
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render
from hotelmanager.models import Hotel
from .forms import UserForm, UserProfileForm
from rooms.models import Room, RoomForm


class HomeView(TemplateView):
    template_name = "home.html"


class HotelView(DetailView):
    model = Hotel
    slug_field = "slugp"
    template_name = "detail.html"


    def get_context_data(self, **kwargs):
        context = super(HotelView, self).get_context_data(**kwargs)
        context['all_rooms_list'] = Room.objects.filter(hotel__slugp=self.kwargs['slug'])
        context['room_form'] = RoomForm
        return context

def login_view(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            login(request, user)
            return HttpResponseRedirect('/')
            # Redirect to success page
        else:
            return HttpResponse("Account disabled")
            # 'Disabled account' error message
    else:
        return HttpResponse("Invalid login")
        # 'Invalid login' error message

@login_required
def logout_view(request):
    logout(request)

    return HttpResponseRedirect('/')

def register_view(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            profile.save()
            registered = True
        else:
            print user_form.errors, profile_form.errors

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request, 'registration.html',
            {'user_form': user_form, 'profile_form': profile_form, 'registered': registered}
            )

rooms/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic

from rooms.models import Room, RoomForm

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from django.views.generic import View

from django.views.generic.edit import FormView


class IndexView(generic.ListView):
    template_name = 'rooms/index.html'
    context_object_name = 'all_rooms_list'

    #@method_decorator(login_required)
    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['room_form'] = RoomForm
        return context

    #@method_decorator(login_required)
    def get_queryset(self):
        return Room.objects.all()


class DetailView(generic.DetailView):
    model = Room
    slug_field = 'number'
    template_name = 'rooms/detail.html'

# not used, but works fine
def add(request):
    print 'test'
    errors = []
    if request.method == 'POST':
        if not request.POST.get('number', ''):
            errors.append('Enter a number of the room.')
        if not errors:
            new = Room(number=request.POST['number'],
                       available=request.POST['available'],
                       prepared=request.POST['prepared'],
                       condignation=request.POST['condignation'])
            new.save()
            return HttpResponseRedirect('/rooms/')
    return render(request, 'rooms/index.html', {'errors': errors})

def add_room(request):
    print "entered add_room function"
    if request.method == 'POST':
        form = RoomForm(request.POST, request.FILES)
        if form.is_valid():
            print "form is valid"
            form.save()
            return HttpResponseRedirect('/rooms/')
        else:
            print "form is NOT valid: ", form.errors
            form = RoomForm()

    return render(request, 'rooms/index.html', {
        'room_form': form,
    })


class AddRoomView(View):
    form_class = RoomForm
    initial = {'key': 'value'}
    template_name = 'rooms/index.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            # <process form cleaned data>
            form.save()
            return HttpResponseRedirect('/rooms/')

        return render(request, self.template_name, {'room_form': form})

class AddRoomVieww(FormView):
    template_name = 'rooms/index.html'
    form_class = RoomForm
    success_url = '/rooms/'

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        #form.send_email()
        return super(AddRoomView, self).form_valid(form)

hotelmanager/templates/rooms/detail.html
{% load staticfiles %}
<h1>{{ room.number }}</h1>

{% if room.img %}
    <img src="..{{ room.img.url }}" alt="Kill Bill" />
{% endif %}

hotelmanager/templates/rooms/index.html
{% extends "base.html" %}

{% block content %}
{% load bootstrap_tags %}


<div class="container">

  <div class="starter-template">

    <div class="panel panel-default">
      <!-- Default panel contents -->
      <div class="panel-heading">Rooms</div>
      <div class="panel-body">
      </div>
      <!-- Table -->
      <table class="table table-bordered">
      {% if all_rooms_list %}
          <tr class="info">
              <td>Number</a></td>
              <td>Available</a></td>
              <td>Prepared</td>
              <td>Condignation</td>
              <td>Equipment</td>
          </tr>

          {% for room in all_rooms_list %}
          {% if room.available %}
              <tr class="success">
          {% else %}
              <tr>
          {% endif %}
              <td><a href="{% url 'rooms:detail' room.number %}">{{ room.number }}</a></td>
              <td>{{ room.available }}</a></td>
              <td>{{ room.prepared }}</td>
              <td>{{ room.condignation }}</td>
              <td>
              {% if room.equipments.all %}
                  {% for e in room.equipments.all %}
                      {{ e }},
                  {% endfor %}
              {% else %}
                  None
              {% endif %}
              </td>
          </tr>
          {% endfor %}
      {% else %}
          <tr><td>No rooms are available.</td></tr>
      {% endif %}
      </table>
    </div>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

  </div>
<form class="form-signin" role="form" action="{% url 'rooms:add_room' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <legend>Add room</legend>
    {{ room_form|as_bootstrap }}
    <div class="form-actions">
      <a href="#back" class="btn">Go back</a>
      <button type="submit" class="btn btn-primary">Save changes</button>
    </div>
</form>




</div><!-- /.container -->


{% endblock %}

hotelmanager/templates/rooms/index_original.html
{% extends "base.html" %}
  
{% block content %}


<div class="container">

  <div class="starter-template">
	
	<div class="panel panel-default">
	  <!-- Default panel contents -->
	  <div class="panel-heading">Rooms</div>
	  <div class="panel-body">
	  </div>
	  <!-- Table -->
	  <table class="table table-bordered">
	  {% if all_rooms_list %}
	  	  <tr class="info">
			  <td>Number</a></td>
			  <td>Available</a></td>
              <td>Prepared</td>  
              <td>Condignation</td> 
              <td>Equipment</td> 
          </tr>
	     
	      {% for room in all_rooms_list %}
	      <tr>
			  <td><a href="{% url 'rooms:detail' room.number %}">{{ room.number }}</a></td>
			  <td>{{ room.available }}</a></td>
              <td>{{ room.prepared }}</td>  
              <td>{{ room.condignation }}</td> 
              <td>{{ room.equipment }}</td> 
          </tr>
	      {% endfor %}
	  {% else %}
	      <tr><td>No rooms are available.</td></tr>
	  {% endif %}
	  </table>
	</div>
	
	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
	

	
	<form class="form-signin" role="form" action="{% url 'rooms:add' %}" method="post">
	{% csrf_token %}
	<h2 class="form-signin-heading">add room</h2>
	<input type="text" name="number" class="form-control" required>
	<input type="text" name="available" class="form-control" required>
	<input type="text" name="prepared" class="form-control" required>
	<input type="text" name="condignation" class="form-control" required>

	<button class="btn btn-lg btn-primary btn-block" type="submit">Add</button>
  </form>

  

  
  </div>

</div><!-- /.container -->

{% endblock %}